name: Deploy nuget package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

  steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: nuget restore
      run: nuget restore src
    - name: build
      run: msbuild src/Seq.App.Telegram/Seq.App.Telegram.csproj /p:Configuration=Release /p:Platform=AnyCPU /v:q
    - name: Create the package
      run: nuget pack src/Seq.App.Telegram/Seq.App.Telegram.csproj -Properties Configuration=Release
    - name: Publish the package to GPR
      run: dotnet nuget push D:\a\Seq.App.Telegram\Seq.App.Telegram\Swisschain.Seq.App.Telegram.0.0.1.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
